version: 0.2

phases:
  install:
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - echo Install source NPM dependencies...
      - cd services/crud-api
      - echo Path is ...
      - pwd
      - npm install 
      - npm install underscore jsonwebtoken bcrypt fs moment uuid4
      - cd ../..
      - echo Path is ...
      - pwd
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the Serverless Framework
      - echo $pwd
      - cd services/database/
      - echo $pwd
      # - sls deploy -v -s $ENV_NAME
      - cd ../crud-api
      - echo pwd
      #- sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed on `date`